name: CI

on:
   push:
     branches: [master]

jobs:
   build:
     runs-on: ubuntu-latest

     steps:
       - uses: actions/checkout@v2

       - name: Build docker-compose
         run: docker-compose -f docker-compose.yml up --build -d
  
   deploy:
     needs: [build]
     runs-on: ubuntu-latest

     steps:
       - uses: actions/checkout@v2

       - name: Set up QEMU
         uses: docker/setup-qemu-action@v1
      
       - name: Set up Docker Buildx
         uses: docker/setup-buildx-action@v1
      
       - name: Login to DockerHub
         uses: docker/login-action@v1 
         with:
           username: ${{ secrets.DOCKERHUB_USERNAME }}
           password: ${{ secrets.DOCKERHUB_TOKEN }}
      
       - name: Build and push App
         id: docker_build
         uses: docker/build-push-action@v2
         with:
           context: .
           file: Dockerfile.app
           push: true
           tags: mtahgg/4302-project:latest

       - name: Build and push DB
         id: docker_build
         uses: docker/build-push-action@v2
         with:
           context: .
           file: Dockerfile.db
           push: true
           tags: mtahgg/4302-project:latest

   image-scan:
     needs: [deploy]
     runs-on: ubuntu-latest
  
     steps:
       - name: Run Dockle
         uses: erzz/dockle-action@v1.1.1
         with:
           image: mtahgg/tic4302-project
           report-format: json
           report-name: dockle-report
          
       - name: Upload Report
         uses: actions/upload-artifact@v2
         if: always()
         with:
           name: Dockle Report
           path: dockle-report.json

   dast:
     needs: [build]
     runs-on: ubuntu-latest

     steps:
      - uses: actions/checkout@v2

      - name: Build docker-compose
        run: docker-compose -f docker-compose.yml up --build -d

      - name: ZAP Scan
        uses: zaproxy/action-full-scan@v0.3.0
        with:
          target: 'http://localhost:8080'
          cmd_options: '-a'

