name: CI

on:
   push:
     branches: [master]

jobs:
   build:
     runs-on: ubuntu-latest

     steps:
       - uses: actions/checkout@v2

       - name: Build docker-compose
         run: docker-compose -f docker-compose.yml up --build -d
    
   image-scan:
     needs: [build]
     runs-on: ubuntu-latest

     steps: 
       - name: Build App
         run: docker image build --file Dockerfile.app

       - name: Build DB
         run: docker image build --file Dockerfile.db


       - name: Check imgages
         run: docker images

       - name: Run Trivy vulnerability scanner
         uses: aquasecurity/trivy-action@master
         with:
          image-ref: '2022-group5-dvpwa_sqli'
          format: 'table'
          exit-code: '1'
          ignore-unfixed: true
          vuln-type: 'os,library'
          severity: 'CRITICAL,HIGH'


