name: CI

on:
   push:
     branches: [master]

jobs:
   build:
     runs-on: ubuntu-latest

     steps:
       - uses: actions/checkout@v2

       - name: Build docker-compose
         run: docker-compose -f docker-compose.yml up --build -d
    
   image-scan:
     needs: [build]
     runs-on: ubuntu-latest

     steps: 
       - uses: actions/checkout@v2

       - name: Build docker-compose
         run: docker-compose -f docker-compose.yml up --build -d

       - name: Check imgages
         run: docker images

       - name: Run Trivy scan on app
         uses: aquasecurity/trivy-action@master
         with:
          image-ref: '2022-group5-dvpwa_sqli'
          format: 'table'
          exit-code: '1'
          ignore-unfixed: true
          vuln-type: 'os,library'
          severity: 'CRITICAL,HIGH'

       - name: Run Trivy scan on db
         uses: aquasecurity/trivy-action@master
         with:
          image-ref: '2022-group5-dvpwa_postgres'
          format: 'table'
          exit-code: '1'
          ignore-unfixed: true
          vuln-type: 'os,library'
          severity: 'CRITICAL,HIGH'

   dast:
     needs: [build]
     runs-on: ubuntu-latest

     steps:
      - uses: actions/checkout@v2

      - name: Build docker-compose
        run: docker-compose -f docker-compose.yml up --build -d

      - name: ZAP Scan
        uses: zaproxy/action-full-scan@v0.3.0
        with:
          target: 'http://localhost:8080'
          cmd_options: '-aT'

